#!/bin/sh

make maintainer-clean
rm -rf m4/libtool.m4 aclocal.m4 config.guess config.sub configure depcomp install-sh compile ltmain.sh Makefile.in missing include/Makefile.in src/Makefile.in src/vahttool/Makefile.in autom4te.cache Makefile include/Makefile src/Makefile src/vahttool/Makefile config.log config.status m4/lt~obsolete.m4 m4/ltoptions.m4 m4/ltsugar.m4 m4/ltversion.m4
